// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apqicmbotolknuwxyvcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcWljbWJvdG9sa251d3h5dmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MzYzMTEsImV4cCI6MjA1MzAxMjMxMX0.yQvaBwougFXsEk6h7Ku0gvs0Pow-ViKQtC9ozUjswfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);